### ISSUE TITLE
test 2

### ISSUE THREAD

**Issue by jonabc** [jonabc/test-repo#37]
references a few things
- [x] an open issue ref jonabc/test-repo#11
- [x] a closed issue jonabc/test-repo#1
- [ ] a pull request  jonabc/test-repo#17
- [ ] a discussion https://github.com/jonabc/test-repo/discussions/36
- [ ] a discussion with review lab ref https://reference-helpers-return-strings.review-lab.github.com/jonabc/test-repo/discussions/36
- [ ] an alert https://github.com/github/github/security/code-scanning/1062
- [ ] an alert with review lab ref https://pipeline-authorization-nil-viewer.review-lab.github.com/github/github/security/code-scanning/1062
- [ ] non reference

### jonab+c readable repo
https://github.com/jonabc/test-repo/issues/11
jonabc/test-repo#11
https://pipeline-authorization-nil-viewer.review-lab.github.com/jonabc/test-repo/issues/11

### jonab readable repo
https://github.com/jonab/test-repo/issues/1
jonab/test-repo#1
https://pipeline-authorization-nil-viewer.review-lab.github.com/jonab/test-repo/issues/1

### jonabc readable repo
https://github.com/github/heart-services/issues/1036
github/heart-services#1036
https://pipeline-authorization-nil-viewer.review-lab.github.com/github/heart-services/issues/1036

# Code scanning
review lab ref: https://pipeline-authorization-nil-viewer.review-lab.github.com/github/github/security/code-scanning/1062
https://github.com/github/github/security/code-scanning/1062

foobar
